# this is the docker compose version
version: '3.0'

# file version 2024-05-29-1000


networks:
    # network for this compose stack
    bei_network_hub:
        driver: bridge
services:
    # beiService runs tomcat with Batch Effects Interface
    beiService:
        networks:
            - bei_network_hub
        # restart this container if it crashes
        restart: always
        # build from sub-directory and Dockerfile
        build:
            context: ./bei-image
            dockerfile: Dockerfile
        container_name: bei_cont_hub
        image: mdabcb/bei_image:2024-05-29-1000
        volumes:
            # external:internal
            # external log path
            - /BEI/LOGS/BEI:/opt/tomcat/logs
            # file with properties and job list for this installation
            - /BEI/BEI/PROPS:/BEA/BEI/PROPS
            # directory for output from BEI, GDCDownload, and MBatch Results
            - /BEI/BEI/OUTPUT:/BEA/BEI/OUTPUT
            # directory for the Batch Effects Website (must be on Linux file system since links to /BEI/OUTOUT are created here)
            - /BEI/BEI/WEBSITE:/BEA/BEI/WEBSITE
            # read-only directory for HG38 map
            - /BEI/BEI/UTILS:/BEA/BEI/UTILS:ro
            # SMW paths for Metabolomics Workbench DAta
            - /BEI/MW_CACHE:/BEA/SMW/MW_CACHE:ro
            - /BEI/MW_ZIP:/BEA/SMW/MW_ZIP
            # read-only file to set time to same in image as on server
            - /etc/localtime:/etc/localtime:ro
        ports:
            # (outside)host port:container port(inside)
            - "8080:8080"
        tty: true
    mbatchService:
        networks:
            - bei_network_hub
        # restart this container if it crashes
        restart: always
        build:
            # build from sub-directory and Dockerfile
            context: ./mbatch-image
            dockerfile: Dockerfile
        container_name: mbatch_cont_hub
        image: mdabcb/mbatch_image:2024-05-29-1000
        volumes:
            # directory for output from BEI, GDCDownload, and MBatch Results external:internal
            - /BEI/BEI/OUTPUT:/BEA/BEI/OUTPUT
            # directory for the Batch Effects Website (must be on Linux file system since links to /BEI/OUTOUT are created here)
            - /BEI/BEI/WEBSITE:/BEA/BEI/WEBSITE
            # SMW paths for Metabolomics Workbench DAta
            - /BEI/MW_CACHE:/BEA/SMW/MW_CACHE:ro
            - /BEI/MW_ZIP:/BEA/SMW/MW_ZIP
            # read-only file to set time to same in image as on server
            - /etc/localtime:/etc/localtime:ro
        links:
            # links required to talk to http://beiService:8080/
            - beiService
    bevService:
        networks:
            - bei_network_hub
        # restart this container if it crashes
        restart: always
        build:
            # build from sub-directory and Dockerfile
            context: ./bev-image
            dockerfile: Dockerfile
        container_name: bev_cont_hub
        # update :latest to desired version
        image: mdabcb/bev_image:2024-05-29-1000
        volumes:
            # external:internal
            # external log path
            - /BEI/LOGS/BEV:/opt/tomcat/logs
            # directory for dap.properties
            - /BEI/BEI/PROPS:/BEA/DAPI_MQA/CONFIG:ro
            # directory for "website" output
            - /BEI/BEI/WEBSITE:/BEA/DAPI_MQA/DATA:ro
            # read-only file to set time to same in image as on server
            - /etc/localtime:/etc/localtime:ro
        ports:
            # (outside)host port:container port(inside)
            - "8081:8080"

