FROM mdabcb/mbatchsa_image:HUB_BEA_VERSION_TIMESTAMP
# CI/CD replaces above with local repo image

# reminder, use {} around environmental variables, otherwise docker uses it as a literal

LABEL edu.mda.bcb.name="Batch Effects Interface: MBatch" \
      edu.mda.bcb.sub="bei" \
      edu.mda.bcb.bea.version="BEA_VERSION_TIMESTAMP" \
      edu.mda.bcb.bea.log="<LOG_DIR>" \
      edu.mda.bcb.bea.start="<START_SCRIPT>" \
      edu.mda.bcb.bea.stop="<STOP_SCRIPT>" \
      edu.mda.bcb.bea.upcheck="<UPCHECK_SCRIPT>"

# create and setup beiuser use to external directory owner
# also, set permissions and ownerships on internal docker directories
# group already exists groupadd -g <GROUPID> beigroup && \
RUN useradd -l -s /bin/bash -d /home/beiuser -u <USERID> -g <GROUPID> beiuser && \
    chown -R beiuser:bcbgroup /home/beiuser && \
    chmod -R 777 /home/beiuser

# make subdirectory in user home for running
RUN mkdir /home/beiuser/mbatch && \
    chown -R beiuser:bcbgroup /home/beiuser/mbatch && \
    chmod -R u+rwx /home/beiuser/mbatch
COPY --chown=beiuser:bcbgroup --chmod=775 installations /home/beiuser/mbatch

# switch from root to beiuser user
USER beiuser

# set working directory for future commands
WORKDIR /home/beiuser/mbatch
CMD /home/beiuser/mbatch/runRproc.bash http://beiService:8080/

