FROM mdabcb/debian_r_java:2020-08-31-0800

# reminder, use {} around environmental variables, otherwise docker uses it as a literal

LABEL edu.mda.bcb.name="MBatch Stand Alone" \
      edu.mda.bcb.version="2019-06-17-1035" \
      edu.mda.bcb.url="http://<server-ip>:8787"

# create and setup docker_tcga use to external directory owner
# also, set permissions and ownerships on internal docker directories
RUN mkdir /home/docker_tcga && \
    useradd -l -s /bin/bash -d /home/docker_tcga -u <USERID> docker_tcga && \
    chown -R docker_tcga:docker_tcga /home/docker_tcga

# create and setup docker_tcga user
# also, set permissions and ownerships on internal docker directories
# make and set ownership and permissions on internal image volume mount locations
# must be done in one step, or could lock permissions in future images
RUN mkdir -p /BEI/MBATCH && \
    mkdir -p /BEI/WEBSITE && \
    mkdir -p /BEI/OUTPUT && \
    chown -R docker_tcga:docker_tcga /BEI && \
    chmod -R u+rwx /BEI

# make subdirectory in user home for running
# COPY is always done as root!!!!
RUN mkdir /home/docker_tcga/mbatch && \
    chown -R docker_tcga:docker_tcga /home/docker_tcga/mbatch && \
    chmod -R u+rwx /home/docker_tcga/mbatch
COPY installations /home/docker_tcga/mbatch

RUN chown -R docker_tcga:docker_tcga /home/docker_tcga && \
    chmod -R u+rwx /home/docker_tcga && \
    ls -l /home/docker_tcga/mbatch

# install MBatch and MBatchUtils separately from above, so can be installed without reperforming above
RUN cd /home/docker_tcga/mbatch && \
    R CMD INSTALL MBatch_*.tar.gz && \
    R CMD INSTALL MBatchUtils_*.tar.gz

# switch from root to docker_tcga user
USER docker_tcga

# set working directory for future commands
WORKDIR /home/docker_tcga/mbatch
CMD ["/bin/bash", "/home/docker_tcga/mbatch/runRproc.bash", "http://beiService:8080/"]

