# this is the docker compose version
version: '3.0'

# file version BEA_VERSION_TIMESTAMP


networks:
    # network for this compose stack
    bei_network_<ENVIRON>:
        driver: bridge
services:
    # beiService runs tomcat with Batch Effects Interface
    beiService:
        networks:
            - bei_network_<ENVIRON>
        # restart this container if it crashes
        restart: always
        # build from sub-directory and Dockerfile
        build:
            context: ./bei-image
            dockerfile: Dockerfile<DC_DF_DVLP>
        container_name: bei_cont_<ENVIRON>
        image: <BEI-IMAGEURL>
        volumes:
            # external:internal
            # external log path
            - <LOGPATH>/BEI:/opt/tomcat/logs
            # file with properties and job list for this installation
            - <PROP-DIR>:/BEA/BEI/PROPS
            # directory for output from BEI, GDCDownload, and MBatch Results
            - <JOB-OUTPUT-DIR>:/BEA/BEI/OUTPUT
            # directory for the Batch Effects Website (must be on Linux file system since links to /BEI/OUTOUT are created here)
            - <WEBSITE-DIR>:/BEA/BEI/WEBSITE
            # read-only directory for HG38 map
            - <UTIL-DIR>:/BEA/BEI/UTILS:ro
            # SMW paths for Metabolomics Workbench DAta
            - <CONFIGPATH>:/BEA/SMW/MW_CACHE:ro
            - <ZIPTMPPATH>:/BEA/SMW/MW_ZIP
            # read-only file to set time to same in image as on server
            - /etc/localtime:/etc/localtime:ro
        ports:
            # (outside)host port:container port(inside)
            - "<BEI-PORT>:8080"
        tty: true
    mbatchService:
        networks:
            - bei_network_<ENVIRON>
        # restart this container if it crashes
        restart: always
        build:
            # build from sub-directory and Dockerfile
            context: ./mbatch-image
            dockerfile: Dockerfile<DC_DF_DVLP>
        container_name: mbatch_cont_<ENVIRON>
        image: <MBATCH-IMAGEURL>
        volumes:
            # directory for output from BEI, GDCDownload, and MBatch Results external:internal
            - <JOB-OUTPUT-DIR>:/BEA/BEI/OUTPUT
            # directory for the Batch Effects Website (must be on Linux file system since links to /BEI/OUTOUT are created here)
            - <WEBSITE-DIR>:/BEA/BEI/WEBSITE
            # SMW paths for Metabolomics Workbench DAta
            - <CONFIGPATH>:/BEA/SMW/MW_CACHE:ro
            - <ZIPTMPPATH>:/BEA/SMW/MW_ZIP
            # read-only file to set time to same in image as on server
            - /etc/localtime:/etc/localtime:ro
        links:
            # links required to talk to http://beiService:8080/
            - beiService
    bevService:
        networks:
            - bei_network_<ENVIRON>
        # restart this container if it crashes
        restart: always
        build:
            # build from sub-directory and Dockerfile
            context: ./bev-image
            dockerfile: Dockerfile<DC_DF_DVLP>
        container_name: bev_cont_<ENVIRON>
        # update :latest to desired version
        image: <BEV-IMAGEURL>
        volumes:
            # external:internal
            # external log path
            - <LOGPATH>/BEV:/opt/tomcat/logs
            # directory for dap.properties
            - <PROP-DIR>:/BEA/DAPI_MQA/CONFIG:ro
            # directory for "website" output
            - <WEBSITE-DIR>:/BEA/DAPI_MQA/DATA:ro
            # read-only file to set time to same in image as on server
            - /etc/localtime:/etc/localtime:ro
        ports:
            # (outside)host port:container port(inside)
            - "<BEV-PORT>:8080"

